# -*- coding: utf-8 -*-
"""Tgs3Dami.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GdxAjLGHQcaxPNaXGqzXCAqvSzLGwpFz
"""

import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.cluster import KMeans
from sklearn.cluster import AgglomerativeClustering
from sklearn.metrics import davies_bouldin_score

df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/00488/Live.csv')
df

df.isnull().sum()

df.drop(['status_id', 'status_published'], axis=1, inplace=True)

df.info()

df['status_type'].unique()

df.drop(['status_id','status_published'], axis=1, inplace=True)

df

X = df.drop(['status_type'], axis=1)
y = df['status_type']

le = LabelEncoder() 
le.fit_transform(y)
y = le.transform(y) # 0.Link 1.Photo 2.Status 3.Video

# X['status_type'].unique()

kmeans2 = KMeans(n_clusters=2, random_state=0) 

kmeans2.fit(X)

centeroid = kmeans2.cluster_centers_

all = pd.DataFrame(centeroid,columns=['num_reactions','num_comments','num_shares','num_likes','num_loves','num_wows','num_hahas','num_sads','num_angrys'])
T = pd.concat((X,all), axis=0)
T

kesimpulan = 1,len(X)/2+1
print('Jadi data Jumlah Nilai Terbanyak Terdapat pada baris',kesimpulan[0],'sampai',int(kesimpulan[1]))

kmeans3 = KMeans(n_clusters=3, random_state=0) 

kmeans3.fit(X)

centeroid = kmeans3.cluster_centers_

all = pd.DataFrame(centeroid,columns=['num_reactions','num_comments','num_shares','num_likes','num_loves','num_wows','num_hahas','num_sads','num_angrys'])
T = pd.concat((X,all), axis=0)
T

ahc2 = AgglomerativeClustering(n_clusters=5, affinity='euclidean', linkage='ward')
ahc2.fit(X)

ahcl = pd.DataFrame(ahc2.labels_,columns=['Label AHC'])
T = pd.concat((X,ahcl), axis=1)
T

DBI = davies_bouldin_score(X, y)

print('Nilai DBI adalah:', DBI)

X = pd.DataFrame(df,columns=['num_reactions','num_comments','num_shares'])

kmeans5 = KMeans(n_clusters=5, random_state=0) 

kmeans5.fit(X)

centeroid = kmeans5.cluster_centers_

all = pd.DataFrame(centeroid,columns=['num_reactions','num_comments','num_shares'])
T = pd.concat((X,all), axis=0)
T

kesimpulan = len(X)/4+1,len(X)/3+1
print('Jadi data Jumlah Nilai Terbanyak Terdapat pada baris',int(kesimpulan[0]),'sampai',kesimpulan[1])

ahc = AgglomerativeClustering(n_clusters=5, affinity='euclidean', linkage='ward')
ahc.fit(X)

ahcl = pd.DataFrame(ahc.labels_,columns=['Label AHC'])
T = pd.concat((X,ahcl), axis=1)
T

DBI = davies_bouldin_score(X, y)

print('Nilai DBI adalah:', DBI)

X = pd.DataFrame(df,columns=['num_loves','num_angrys'])

kmeans6 = KMeans(n_clusters=6, random_state=0) 

kmeans6.fit(X)

centeroid = kmeans6.cluster_centers_

all = pd.DataFrame(centeroid,columns=['num_loves','num_angrys'])
T = pd.concat((X,all), axis=0)
T[7040:7056]

kesimpulan = len(X)/5+1,len(X)/4+1
print('Jadi data Jumlah Nilai Terbanyak Terdapat pada baris',int(kesimpulan[0]),'sampai',int(kesimpulan[1]))

ahc = AgglomerativeClustering().fit(X)

ahcl = pd.DataFrame(ahc.labels_,columns=['Label AHC'])
T = pd.concat((X,ahcl), axis=1)
T

DBI = davies_bouldin_score(X, y)

print('Nilai DBI adalah:', DBI)